### ISSUE TITLE
dolphin berries appearing on land with a water source block

### ISSUE THREAD

**Issue by cintreck** [Cam11062/Strange-Berries#8]

**Comment by reiieva** [comment]
Hi there, sorry for the late response! This is expected in version 2.3.2 (the 1.19.2 BETA version) of Strange Berries hence why I labelled the version as a beta. 

When working on the 1.19.2 version, I was unable to implement underwater generation the same way I did in other versions and as I was in a rush to release said version, I intentionally made it so they generate on land but still must be planted in a water source. I did plan on fixing this for a while although I decided not to as I didn't want to continue working on the 1.19.2 version as from my perspective I felt as if there was no need for me to. 

I know this isn't the response you may be looking for but I have no intentions of working on the 1.19.2 version at this time and I probably never will with future versions being my only priority. Although I should let you know that releases for 1.20 and onwards do not have this issue present so updating to a newer version of Minecraft and Strange Berries would be a solution to this problem.

**Comment by reiieva** [comment]
Closed due to inactivity.
